### ISSUE TITLE
Memory exhaustion issue when loading pi0_base params

### ISSUE THREAD

**Issue by pranavguru** [Physical-Intelligence/openpi#376]
Hi,

I am trying to get the pi_0 base model to run inference on a single L4 GPU instance (24 GB VRAM), but my program crashes with a resource exhaustion error when I try to load the model parameters:

**_jaxlib.xla_extension.XlaRuntimeError: RESOURCE_EXHAUSTED: Failed to allocate request for 4.50GiB (4831838208B) on device ordinal 0_**

This error is also preceded by a  warning:

**_external/xla/xla/hlo/transforms/simplifiers/hlo_rematerialization.cc:3021] Can't reduce memory use below 8.64GiB (9274958193 bytes) by rematerialization; only reduced to 8.92GiB (9576089592 bytes), down from 9.18GiB (9861339444 bytes) originally_**

When I run the code provided in inference.ipynb to infer using a fine-tuned checkpoint (eg: pi0_aloha, pi0_droid, etc), it works without any issues:

**config = _config.get_config("pi0_aloha_sim")
checkpoint_dir = download.maybe_download("s3://openpi-assets/checkpoints/pi0_aloha_sim")
key = jax.random.key(0)
model = config.model.load(_model.restore_params(checkpoint_dir / "params"))**

However, when I try to do the same with the pi0_base model, I get the error mentioned above:

**key = jax.random.key(0)
checkpoint_dir = download.maybe_download("s3://openpi-assets/checkpoints/pi0_base")
config = pi0.Pi0Config()
model = config.create(key)
params = _model.restore_params(checkpoint_dir / "params")
model.load(params)**

The program crashes at the _model.restore_params line with the resource exhaustion error.

Why is this happening? If I can run the fine-tuned checkpoints without any issues, I should be able to run inference using the base model as well right? Is a 24 GB VRAM GPU not sufficient for this? (I doubt this is the case as the readme says that for inference, around 8 GB is sufficient)

I also tried setting the following env variables, but it didn't work:

**os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
os.environ['XLA_PYTHON_CLIENT_MEM_FRACTION'] = '0.8'  # Use 80% of available GPU memory
os.environ['XLA_PYTHON_CLIENT_ALLOCATOR'] = 'platform'  # Use a more memory-efficient allocator**

Any help would be appreciated, thanks!

**Comment by haohuanw** [comment]
so `model = config.create(key)` will eager initializes the model weights by default (which is float32, that will use roughly ~16G) then restore params also creates a copy in memory which is why it uses all memories.

**Comment by pranavguru** [comment]
Understood, works for me now after I did:

config = pi0.Pi0Config()
model = config.load(
    _model.restore_params(download.maybe_download("s3://openpi-assets/checkpoints/pi0_base/params"))
)

Thank you for your help!
