### ISSUE TITLE
Training process gets stuck at step=0

### ISSUE THREAD

**Issue by 159chenJie159** [Physical-Intelligence/openpi#483]
I am training pi0_fast using the LoRA method. When I perform training on a single GPU, everything works normally and the entire training process can be completed. However, when I use 2 or 4 GPUs for training, the process gets stuck. I think i have correctly modified the config.py.

The issue does not occur consistently — I have had successful runs in the past. Since there is no error being thrown, it has become difficult for me to pinpoint the cause of the problem. I would greatly appreciate any help or suggestions.

**Comment by kodaekwan** [comment]
I was in a similar situation. In my case, the issue was due to NCCL problems between multiple GPUs. Setting NCCL_P2P_DISABLE=0 along with the XLA_PYTHON_CLIENT_MEM_FRACTION option resolved the issue. If you analyze the Open-PI code, you’ll notice that it runs training with JAX and has a default setup that differs from typical development PCs. Also, be aware that multi-GPU setups may require adjustments in BIOS settings. I hope this helps resolve your issue.

**Comment by haohuanw** [comment]
looks to be duplicates of https://github.com/Physical-Intelligence/openpi/issues/480

please reopen the other issue if it persists.

**Comment by 159chenJie159** [comment]
"I configured the environment variable NCCL_P2P_DISABLE=1, which proved to be effective. Thank you for your help."
