### ISSUE TITLE
GPU crash with `action_horizon > 1` (CUDA ERROR ILLEGAL ADDRESS on H100s)

### ISSUE THREAD

**Issue by dbalaram** [Physical-Intelligence/openpi#539]
I'm encountering a crash when training with `action_horizon > 1` using JAX on NVIDIA H100 GPUs.

### Setup:
* **GPU**: 8× NVIDIA H100
* **CUDA**: 12.5
* **Driver**: 555.42.06
* **Docker Base Image**: `nvcr.io/nvidia/pytorch:23.12-py3`
* **JAX backend**: GPU
* **Works fine** when `action_horizon = 1` (default)

### Failure:
When I set `action_horizon = 2` or `3`, I get:

```
CUDA error: : CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered
...
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: CUDA error: Could not synchronize CUDA stream
```

Full stack trace includes dozens of module unload failures and `pjrt_stream_executor_client.cc:1524` crash.

### Confirmed:

* Works perfectly on CPU (even with `action_horizon = 2/3`) — model and data are valid
* Shapes are correct throughout forward and data loading
* Model trains fine on GPU with `action_horizon = 1`, batch size = 8, runs on all 8 GPUs (H100)

### Hypothesis:

The bug probably appears during loss calculation (in `ptrain_step`) with multi-step actions. I suspect the issue is triggered by inf/nans in the grad calculation step OR invalid memory access due to sequence formatting, possibly due to `delta_timestamps` logic in LeRobotDataset([https://github.com/Physical-Intelligence/openpi/blob/main/src/openpi/training/data_loader.py#L139](https://github.com/Physical-Intelligence/openpi/blob/main/src/openpi/training/data_loader.py#L139))or transform pipelines.

### How to Reproduce:

```bash
# Use GPU and set
action_horizon = 2  # or 3

# CPU (works)
jax.config.update("jax_platform_name", "cpu")
```

### Questions:

* Is there a recommended way to debug exactly which operation in ptrain_step causes the illegal memory access?
* Are there known issues with multi-step action sequences in JAX when using GPU/XLA?
* Could this be caused by how delta_timestamps influences sequence generation in LeRobotDataset?
* Has anyone else observed this crash when fine-tuning OpenPI with non-default datasets (e.g., custom or LeRobot-format datasets) and action_horizon > 1?

Happy to share more context or logs if helpful.

Thanks!

**Comment by kvablack** [comment]
That's very strange. It's definitely not caused by inf/nans, and it's unlikely to have anything to do with the dataloader.

Could you try with a more bare-bones Docker container? In my experience, some sort of conflict between the system-installed CUDA and pip-installed JAX is the most likely culprit. The only thing you need installed at a system level is the NVIDIA driver; JAX takes care of the rest. (Thanks to uv, you don't even need Python installed!)

`nvcr.io/nvidia/pytorch:23.12-py3` is pretty heavy-weight and comes with all sorts of stuff installed.

**Comment by dbalaram** [comment]
Yes it was an issue with JAX and CUDA version. Making them compatible fixed my issue, thanks!

**Comment by Alicia320** [comment]
hi  I'm facing this problem as well,would you mind give me the version of your compatible JAX and CUDA? Thanks a lot!!

**Comment by Loki-Lu** [comment]
Hi, I have the same question. How to find a suitable jax+cuda version? Thanks a lot!
