### ISSUE TITLE
CUDA out of memory when using pytorch to finetune in RTX4090

### ISSUE THREAD

**Issue by ZijianWu1121** [Physical-Intelligence/openpi#677]
I use the pytorch to finetune the PI0_base.

the config I set shows below:

    TrainConfig(
        name="test_pi0",
        model=pi0_config.Pi0Config(paligemma_variant="gemma_2b_lora", action_expert_variant="gemma_300m_lora"),
        data=LeRobotR1ProDataConfig(
            repo_id="test/apple",
            base_config=DataConfig(prompt_from_task=True),
            extra_delta_transform=True,
        ),
        weight_loader=weight_loaders.CheckpointWeightLoader("gs://openpi-assets/checkpoints/pi0_base/params"),
        num_train_steps=20_000,
        freeze_filter=pi0_config.Pi0Config(paligemma_variant="gemma_2b_lora", action_expert_variant="gemma_300m_lora").get_freeze_filter(),
        ema_decay=None,
        num_workers=1, batch_size=1, fsdp_devices=1, # for single one RTX4090
        pytorch_weight_path="/home/test/.cache/openpi/openpi-assets/checkpoints/pi0_base_pytorch"
    ),

but the log shows CUDA out of memory:

rist_image': 'observation.images.right_wrist_rgb', 'observation/state': 'state', 'actions': 'actions', 'prompt': 'prompt'})], outputs=()), data_transforms=Group(inputs=(R1ProInputs(model_type=<ModelType.PI0: 'pi0'>), DeltaActions(mask=(True, True, True, True, True, True, True, False))), outputs=(AbsoluteActions(mask=(True, True, True, True, True, True, True, False)), R1ProOutputs())), model_transforms=Group(inputs=[InjectDefaultPrompt(prompt=None), ResizeImages(height=224, width=224), TokenizePrompt(tokenizer=<openpi.models.tokenizer.PaligemmaTokenizer object at 0x7b9f71ccf1d0>, discrete_state_input=False), PadStatesAndActions(model_action_dim=32)], outputs=()), use_quantile_norm=False, action_sequence_keys=('actions',), prompt_from_task=True, rlds_data_dir=None, behavior_dataset_root=None, action_space=None, filter_dict_path=None, episodes_index=None) (55077:data_loader.py:268)
Resolving data files: 100%|████████████████████████████████████████████████████████████████████████████████| 118/118 [00:00<00:00, 940927.51it/s]
09:49:01.746 [I] local_batch_size: 1                                                              (55077:data_loader.py:374)
INFO:2025-09-19 09:49:01,817:jax._src.xla_bridge:925: Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
09:49:01.817 [I] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig' (55077:xla_bridge.py:925)
INFO:2025-09-19 09:49:01,818:jax._src.xla_bridge:925: Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory
09:49:01.818 [I] Unable to initialize backend 'tpu': INTERNAL: Failed to open libtpu.so: libtpu.so: cannot open shared object file: No such file or directory (55077:xla_bridge.py:925)
09:49:29.395 [I] Enabled gradient checkpointing for PI0Pytorch model                              (55077:pi0_pytorch.py:133)
09:49:29.395 [I] Enabled gradient checkpointing for memory optimization                           (55077:train_pytorch.py:414)
09:49:29.396 [I] Step 0 (after_model_creation): GPU memory - allocated: 7.02GB, reserved: 7.09GB, free: 0.07GB, peak_allocated: 7.02GB, peak_reserved: 7.09GB (55077:train_pytorch.py:304)
09:49:29.396 [I] Loading weights from: /home/wzj/.cache/openpi/openpi-assets/checkpoints/pi0_base_pytorch (55077:train_pytorch.py:443)
09:49:30.258 [I] Loaded PyTorch weights from /home/wzj/.cache/openpi/openpi-assets/checkpoints/pi0_base_pytorch (55077:train_pytorch.py:449)
09:49:30.261 [I] Running on: wzj | world_size=1                                                   (55077:train_pytorch.py:486)
09:49:30.261 [I] Training config: batch_size=1, effective_batch_size=1, num_train_steps=20000     (55077:train_pytorch.py:489)
09:49:30.261 [I] Memory optimizations: gradient_checkpointing=True                                (55077:train_pytorch.py:492)
09:49:30.261 [I] LR schedule: warmup=1000, peak_lr=2.50e-05, decay_steps=30000, end_lr=2.50e-06   (55077:train_pytorch.py:493)
09:49:30.261 [I] Optimizer: AdamW, weight_decay=1e-10, clip_norm=1.0                              (55077:train_pytorch.py:496)
09:49:30.261 [I] EMA is not supported for PyTorch training                                        (55077:train_pytorch.py:499)
09:49:30.261 [I] Training precision: bfloat16                                                     (55077:train_pytorch.py:500)
Training:   0%|                                                                                                        | 0/20000 [00:00<?, ?it/s]09:50:05.882 [I] Step 0 (after_backward): GPU memory - allocated: 13.34GB, reserved: 13.55GB, free: 0.21GB, peak_allocated: 13.63GB, peak_reserved: 13.81GB (55077:train_pytorch.py:304)
Traceback (most recent call last):
  File "/home/wzj/vla/pi_b1k/openpi_private/scripts/train_pytorch.py", line 632, in <module>
    main()
  File "/home/wzj/vla/pi_b1k/openpi_private/scripts/train_pytorch.py", line 628, in main
    train_loop(config)
  File "/home/wzj/vla/pi_b1k/openpi_private/scripts/train_pytorch.py", line 549, in train_loop
    optim.step()
  File "/home/wzj/vla/pi_b1k/openpi_private/.venv/lib/python3.11/site-packages/torch/optim/optimizer.py", line 485, in wrapper
    out = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/wzj/vla/pi_b1k/openpi_private/.venv/lib/python3.11/site-packages/torch/optim/optimizer.py", line 79, in _use_grad
    ret = func(self, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/wzj/vla/pi_b1k/openpi_private/.venv/lib/python3.11/site-packages/torch/optim/adam.py", line 236, in step
    has_complex = self._init_group(
                  ^^^^^^^^^^^^^^^^^
  File "/home/wzj/vla/pi_b1k/openpi_private/.venv/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 838, in _fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/wzj/vla/pi_b1k/openpi_private/.venv/lib/python3.11/site-packages/torch/optim/adam.py", line 176, in _init_group
    state["exp_avg"] = torch.zeros_like(
                       ^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB. GPU 0 has a total capacity of 23.63 GiB of which 226.56 MiB is free. Including non-PyTorch memory, this process has 22.77 GiB memory in use. Of the allocated memory 21.98 GiB is allocated by PyTorch, and 320.27 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)

it was OK when I used jax to train. why?

**Comment by vcozzolino** [comment]
I'm facing the same issue.

**Comment by vcozzolino** [comment]
I found a workaround to get the training started (can't promise on the model training quality as the optimizer changes).

The CUDA out-of-memory error during optim.step() or even at optimizer creation when training large models with Adam/Adafactor, it’s often because the optimizer states (1st/2nd moment buffers) are too large to fit on your GPU, even with gradient checkpointing, bf16, and small batch sizes. Pi0.5 uses AdamW, which is quite memory hungry during the initialization step.

A simple and effective solution is to use an 8-bit optimizer from [bitsandbytes](https://github.com/TimDettmers/bitsandbytes)
, which reduces memory usage by ~75% while keeping behavior compatible with AdamW.

Additionally, in my solution, I also move the buffers to the CPU to reduce GPU memory pressure.

Here are the drop-in changes for the code:

1. Install bitsandbytes with `uv pip install bitsandbytes`
2. Replace AdamW with AdamW8bit in `train_pytorch.py` roughly around line 450:
```
    optim = None
    if config.use_8bit_adam:
        import bitsandbytes as bnb
        optim = bnb.optim.AdamW8bit(
            model.parameters(),
            lr=peak_lr,
            betas=(config.optimizer.b1, config.optimizer.b2),
            weight_decay=config.optimizer.weight_decay,
            eps=config.optimizer.eps
        )

        # move all optimizer state tensors to CPU
        # increse step exeecution time but save GPU memory
        for state in optim.state.values():
            for k, v in state.items():
                if isinstance(v, torch.Tensor):
                    state[k] = v.cpu()

    else:
    # Create optimizer with config parameters
        optim = torch.optim.AdamW(
            model.parameters(),
            lr=peak_lr,
            betas=(config.optimizer.b1, config.optimizer.b2),
            eps=config.optimizer.eps,
            weight_decay=config.optimizer.weight_decay
        )
```
3. Add in `TrainConfig` class in `config.py` a parameter to enable/disable the optimization:
```
# If true, will use 8-bit Adam optimizer from bitsandbytes.
use_8bit_adam: bool = False
```

I'm currently able to train the model, even tho I had to further reduce batch size to 8 on my RTX 4090.

Command:
`XLA_PYTHON_CLIENT_MEM_FRACTION=0.99 uv run scripts/train_pytorch.py <your_train_config> --exp-name=<exp_name> --overwrite --batch-size=8 --num-workers=1 --use-8bit-adam`

**Comment by tahsinkose** [comment]
Thanks @vcozzolino! It at least trains now.

**Comment by weiheng-liu** [comment]
> I found a workaround to get the training started (can't promise on the model training quality as the optimizer changes).
> 
> The CUDA out-of-memory error during optim.step() or even at optimizer creation when training large models with Adam/Adafactor, it’s often because the optimizer states (1st/2nd moment buffers) are too large to fit on your GPU, even with gradient checkpointing, bf16, and small batch sizes. Pi0.5 uses AdamW, which is quite memory hungry during the initialization step.
> 
> A simple and effective solution is to use an 8-bit optimizer from [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) , which reduces memory usage by ~75% while keeping behavior compatible with AdamW.
> 
> Additionally, in my solution, I also move the buffers to the CPU to reduce GPU memory pressure.
> 
> Here are the drop-in changes for the code:
> 
> 1. Install bitsandbytes with `uv pip install bitsandbytes`
> 2. Replace AdamW with AdamW8bit in `train_pytorch.py` roughly around line 450:
> 
> ```
>     optim = None
>     if config.use_8bit_adam:
>         import bitsandbytes as bnb
>         optim = bnb.optim.AdamW8bit(
>             model.parameters(),
>             lr=peak_lr,
>             betas=(config.optimizer.b1, config.optimizer.b2),
>             weight_decay=config.optimizer.weight_decay,
>             eps=config.optimizer.eps
>         )
> 
>         # move all optimizer state tensors to CPU
>         # increse step exeecution time but save GPU memory
>         for state in optim.state.values():
>             for k, v in state.items():
>                 if isinstance(v, torch.Tensor):
>                     state[k] = v.cpu()
> 
>     else:
>     # Create optimizer with config parameters
>         optim = torch.optim.AdamW(
>             model.parameters(),
>             lr=peak_lr,
>             betas=(config.optimizer.b1, config.optimizer.b2),
>             eps=config.optimizer.eps,
>             weight_decay=config.optimizer.weight_decay
>         )
> ```
> 
> 3. Add in `TrainConfig` class in `config.py` a parameter to enable/disable the optimization:
> 
> ```
> # If true, will use 8-bit Adam optimizer from bitsandbytes.
> use_8bit_adam: bool = False
> ```
> 
> I'm currently able to train the model, even tho I had to further reduce batch size to 8 on my RTX 4090.
> 
> Command: `XLA_PYTHON_CLIENT_MEM_FRACTION=0.99 uv run scripts/train_pytorch.py <your_train_config> --exp-name=<exp_name> --overwrite --batch-size=8 --num-workers=1 --use-8bit-adam`

Can we use this method to train a PyTorch model with LoRA? The README says LoRA isn’t supported right now ToT.

**Comment by Kimho666** [comment]
I also face this problem, I set batch_size=1, It is also out of memory.

**Comment by weiheng-liu** [comment]
> I also face this problem, I set batch_size=1, It is also out of memory.

Did you train this torch model with lora?

**Comment by vcozzolino** [comment]
> > I found a workaround to get the training started (can't promise on the model training quality as the optimizer changes).
> > The CUDA out-of-memory error during optim.step() or even at optimizer creation when training large models with Adam/Adafactor, it’s often because the optimizer states (1st/2nd moment buffers) are too large to fit on your GPU, even with gradient checkpointing, bf16, and small batch sizes. Pi0.5 uses AdamW, which is quite memory hungry during the initialization step.
> > A simple and effective solution is to use an 8-bit optimizer from [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) , which reduces memory usage by ~75% while keeping behavior compatible with AdamW.
> > Additionally, in my solution, I also move the buffers to the CPU to reduce GPU memory pressure.
> > Here are the drop-in changes for the code:
> > 
> > 1. Install bitsandbytes with `uv pip install bitsandbytes`
> > 2. Replace AdamW with AdamW8bit in `train_pytorch.py` roughly around line 450:
> > 
> > ```
> >     optim = None
> >     if config.use_8bit_adam:
> >         import bitsandbytes as bnb
> >         optim = bnb.optim.AdamW8bit(
> >             model.parameters(),
> >             lr=peak_lr,
> >             betas=(config.optimizer.b1, config.optimizer.b2),
> >             weight_decay=config.optimizer.weight_decay,
> >             eps=config.optimizer.eps
> >         )
> > 
> >         # move all optimizer state tensors to CPU
> >         # increse step exeecution time but save GPU memory
> >         for state in optim.state.values():
> >             for k, v in state.items():
> >                 if isinstance(v, torch.Tensor):
> >                     state[k] = v.cpu()
> > 
> >     else:
> >     # Create optimizer with config parameters
> >         optim = torch.optim.AdamW(
> >             model.parameters(),
> >             lr=peak_lr,
> >             betas=(config.optimizer.b1, config.optimizer.b2),
> >             eps=config.optimizer.eps,
> >             weight_decay=config.optimizer.weight_decay
> >         )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 3. Add in `TrainConfig` class in `config.py` a parameter to enable/disable the optimization:
> > 
> > ```
> > # If true, will use 8-bit Adam optimizer from bitsandbytes.
> > use_8bit_adam: bool = False
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm currently able to train the model, even tho I had to further reduce batch size to 8 on my RTX 4090.
> > Command: `XLA_PYTHON_CLIENT_MEM_FRACTION=0.99 uv run scripts/train_pytorch.py <your_train_config> --exp-name=<exp_name> --overwrite --batch-size=8 --num-workers=1 --use-8bit-adam`
> 
> Can we use this method to train a PyTorch model with LoRA? The README says LoRA isn’t supported right now ToT.

For my Pi05 custom training config, I added this line to attempt to enable LORA:
`freeze_filter=pi0_config.Pi0Config(paligemma_variant="gemma_2b_lora", action_expert_variant="gemma_300m_lora").get_freeze_filter()`.

It trained the model without issues, and I can confirm that using the modified 8bit optimizer I recommended works.

**Comment by weiheng-liu** [comment]
> > > I found a workaround to get the training started (can't promise on the model training quality as the optimizer changes).
> > > The CUDA out-of-memory error during optim.step() or even at optimizer creation when training large models with Adam/Adafactor, it’s often because the optimizer states (1st/2nd moment buffers) are too large to fit on your GPU, even with gradient checkpointing, bf16, and small batch sizes. Pi0.5 uses AdamW, which is quite memory hungry during the initialization step.
> > > A simple and effective solution is to use an 8-bit optimizer from [bitsandbytes](https://github.com/TimDettmers/bitsandbytes) , which reduces memory usage by ~75% while keeping behavior compatible with AdamW.
> > > Additionally, in my solution, I also move the buffers to the CPU to reduce GPU memory pressure.
> > > Here are the drop-in changes for the code:
> > > 
> > > 1. Install bitsandbytes with `uv pip install bitsandbytes`
> > > 2. Replace AdamW with AdamW8bit in `train_pytorch.py` roughly around line 450:
> > > 
> > > ```
> > >     optim = None
> > >     if config.use_8bit_adam:
> > >         import bitsandbytes as bnb
> > >         optim = bnb.optim.AdamW8bit(
> > >             model.parameters(),
> > >             lr=peak_lr,
> > >             betas=(config.optimizer.b1, config.optimizer.b2),
> > >             weight_decay=config.optimizer.weight_decay,
> > >             eps=config.optimizer.eps
> > >         )
> > > 
> > >         # move all optimizer state tensors to CPU
> > >         # increse step exeecution time but save GPU memory
> > >         for state in optim.state.values():
> > >             for k, v in state.items():
> > >                 if isinstance(v, torch.Tensor):
> > >                     state[k] = v.cpu()
> > > 
> > >     else:
> > >     # Create optimizer with config parameters
> > >         optim = torch.optim.AdamW(
> > >             model.parameters(),
> > >             lr=peak_lr,
> > >             betas=(config.optimizer.b1, config.optimizer.b2),
> > >             eps=config.optimizer.eps,
> > >             weight_decay=config.optimizer.weight_decay
> > >         )
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 
> > > 3. Add in `TrainConfig` class in `config.py` a parameter to enable/disable the optimization:
> > > 
> > > ```
> > > # If true, will use 8-bit Adam optimizer from bitsandbytes.
> > > use_8bit_adam: bool = False
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I'm currently able to train the model, even tho I had to further reduce batch size to 8 on my RTX 4090.
> > > Command: `XLA_PYTHON_CLIENT_MEM_FRACTION=0.99 uv run scripts/train_pytorch.py <your_train_config> --exp-name=<exp_name> --overwrite --batch-size=8 --num-workers=1 --use-8bit-adam`
> > 
> > 
> > Can we use this method to train a PyTorch model with LoRA? The README says LoRA isn’t supported right now ToT.
> 
> For my Pi05 custom training config, I added this line to attempt to enable LORA: `freeze_filter=pi0_config.Pi0Config(paligemma_variant="gemma_2b_lora", action_expert_variant="gemma_300m_lora").get_freeze_filter()`.
> 
> It trained the model without issues, and I can confirm that using the modified 8bit optimizer I recommended works.

Thanks a lot！Based on your previous training experience, does using an 8-bit optimizer affect the final performance?

**Comment by vcozzolino** [comment]
> Thanks a lot！Based on your previous training experience, does using an 8-bit optimizer affect the final performance?

No, based on my tests with the model I trained, using an 8-bit optimizer did not impact the final performance; the success rate was still very high when I deployed and used the model on the real robot.

In the end, the optimizer's job is convergence: if the model gets there, it's successful. Although diffusion models involve a more complicated, time-dependent optimization process, an 8-bit optimizer is generally fine as long as the model converges stably.

**Comment by weiheng-liu** [comment]
> > Thanks a lot！Based on your previous training experience, does using an 8-bit optimizer affect the final performance?
> 
> No, based on my tests with the model I trained, using an 8-bit optimizer did not impact the final performance; the success rate was still very high when I deployed and used the model on the real robot.
> 
> In the end, the optimizer's job is convergence: if the model gets there, it's successful. Although diffusion models involve a more complicated, time-dependent optimization process, an 8-bit optimizer is generally fine as long as the model converges stably.

Got it, thanks!
